# Generated by Django 5.2.4 on 2025-07-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["product_id__name"]},
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="product",
            new_name="product_id",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product_id")},
        ),
    ]
